name: Mindlfex
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.4.1
  firebase_auth_platform_interface: ^7.5.1
  firebase_core: ^3.10.1
  cloud_firestore: ^5.6.2
  table_calendar: ^3.0.0
  firebase_analytics: ^11.4.1
  cupertino_icons: ^1.0.8
  icons_plus: ^5.0.0
  curved_navigation_bar: ^1.0.6
  carousel_slider: ^5.0.0
  url_launcher: ^6.0.0-nullsafety.6
  video_player: ^2.3.0

  youtube_player_flutter: ^9.1.1
  flutter_inappwebview: ^6.1.5 # Check for latest version
  email_validator: ^3.0.0

dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/ULOG.png
    - assets/images/bg1.png
    - assets/images/BOWLING_BALL.jpg
    - assets/images/color_hoops.jpg
    - assets/images/row_a_boat.jpg
    - assets/images/beat_saber.jpg
    - assets/images/VRGAMES.png
    - assets/images/VIDEOCON.png
    - assets/images/feedback-two.png
    - assets/images/doctorAdd.jpg
    - assets/images/LOGO.png
